<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="firefly" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg namespace)" />  
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/firefly.dae" />
  <xacro:property name="mass" value="1e-3" /> <!-- 1.5 [kg] -->
  <xacro:property name="body_width" value="0.3" /> <!-- 0.1 [m] -->
  <xacro:property name="body_height" value="0.48" /> <!-- 0.16 [m] -->
  <xacro:property name="mass_rotor" value="0.0001" /> <!-- 0.005 [kg] -->
  <xacro:property name="arm_length" value="0.645" /> <!-- 0.215 [m] -->
  <xacro:property name="rotor_offset_top" value="0.111" /> <!-- 0.037 [m] -->
  <xacro:property name="radius_rotor" value="0.3" /> <!-- 0.1 [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="8380000" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929" iyz="0.0" izz="0.0977" /> <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="0 ${arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${cos30*arm_length} ${sin30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="4"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="0 -${arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="5"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${cos30*arm_length} -${sin30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>


  <!-- Import Transmissions -->
  <xacro:include filename="$(find uav-cable-suspended-robots-ros-pkg)/urdf/licasa1.transmission.xacro" />
  <xacro:LiCAS_A1_transmission name="LiCAS_A1" hardware_interface1="hardware_interface/PositionJointInterface" hardware_interface2="hardware_interface/EffortJointInterface" /> 
  
  <!-- Import Gazebo plugins 
  <xacro:include filename="$(find uav-cable-suspended-robots-ros-pkg)/gazebo/gazebo_licasa1.urdf.xacro"/> -->
  
  <gazebo>
    <plugin name="gazebo_ros_controller" filename="libgazebo_ros_control.so">
      <robotNamespace>/firefly</robotNamespace> 
    </plugin> 

    <!-- <plugin name="ShouldersControlPlugin" filename="libShouldersControlPlugin.so">
      <robotNamespace>/firefly</robotNamespace> 
    </plugin> -->
  </gazebo>


  <!-- TESTBENCH -->
  <joint name="fixed_joint" type="fixed">
    <origin xyz="0 0 0"/>
    <parent link="firefly/base_link"/>
    <child link="testbench"/> 
  </joint> 
  
  <link name="testbench">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="20" /> <!-- 10 -->
      <inertia ixx="1e-03" ixy="0.0" ixz="0.0" iyy="1e-03" iyz="0.0" izz="1e-03"/>
    </inertial>
    <!-- <visual> -->
      <!-- <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.15 0.15 0.01"/>
      </geometry> -->
      <!-- <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Assembly_X4.stl" scale=".001 .001 .001"/>
       </geometry> -->
    <!-- </visual> -->
  </link> 
  
  <!-- CABLES -->
  <joint name="revolute_joint_z" type="revolute" >
    <parent link="testbench"/>
    <child link="bar_link_z" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.517" friction="0.0"/>
    <limit effort="10" lower="${-360/180*pi}" upper="${360/180*pi}" velocity="6"/>
  </joint>
  
  <link name="bar_link_z">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 -0.4"/>
      <mass value="1e-3"/> <!-- 1 -->
      <inertia ixx="0.313" ixy="0.0" ixz="0.0" iyy="0.363" iyz="0.0" izz="0.745"/>
    </inertial>
  </link>
  
  <joint name="revolute_joint_x" type="revolute" >
    <parent link="bar_link_z" />
    <child link="bar_link_x" />
    <axis xyz="1 0 0" />
    <dynamics damping="1.33" friction="0.0"/>
    <limit effort="10.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>    
  </joint>
  
  <link name="bar_link_x">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 -0.174"/>
      <mass value="1e-3"/> <!-- 4.237 -->
      <inertia ixx="0.313" ixy="0.0" ixz="0.0" iyy="0.363" iyz="0.0" izz="0.745"/>
    </inertial>
  </link>
  
  <joint name="revolute_joint_y" type="revolute" >
    <parent link="bar_link_x" />
    <child link="bar_link_y" />
    <axis xyz="0 1 0" />
    <dynamics damping="1.311" friction="0.0"/>
    <limit effort="10.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="bar_link_y">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 -0.824"/>
       <mass value="1e-3"/> <!-- 5.032 -->
      <inertia ixx="0.313" ixy="0.0" ixz="0.0" iyy="0.363" iyz="0.0" izz="0.745"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.5"/>
      <geometry>
        <cylinder length="1.0" radius="0.01"/>
      </geometry>
    </visual>
  </link>
  
  
  <!-- SHOULDER -->
  <joint name="shoulder_joint_z" type="revolute" >
    <origin xyz="0 0 -1.0"/>
    <parent link="bar_link_y"/>
    <child link="shoulder_link_z"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="6.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="shoulder_link_z">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.639"/>
      <inertia ixx="3.02e-3" ixy="0" ixz="0" iyy="8.64e-4" iyz="0" izz="3.39e-3"/>
    </inertial>
  </link>
  
  <joint name="shoulder_joint_x" type="revolute" >
    <origin xyz="0 0 0"/>
    <parent link="shoulder_link_z"/>
    <child link="shoulder_link_x"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="6.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="shoulder_link_x">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.639"/>
      <inertia ixx="3.02e-3" ixy="0" ixz="0" iyy="8.64e-4" iyz="0" izz="3.39e-3"/>
    </inertial>
  </link>
  
  
  <joint name="shoulder_joint_y" type="revolute" >
    <origin xyz="0 0 0"/>
    <parent link="shoulder_link_x"/>
    <child link="shoulder_link_y"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="6.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="shoulder_link_y">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.639"/>
      <inertia ixx="3.02e-3" ixy="0" ixz="0" iyy="8.64e-4" iyz="0" izz="3.39e-3"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Pitch_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Pitch_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  
  <!-- LEFT ARM-->
  <joint name="LiCAS_A1_q1_1" type="revolute">
    <origin xyz="0 0.14 0.0"/>
    <parent link="shoulder_link_y"/>
    <child link="left_shoulder_roll"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-90/180*pi}" upper="${90/180*pi}" velocity="6"/>
  </joint> 
  
  <link name="left_shoulder_roll">
    <inertial>
      <origin xyz="0 0.0236 -0.00946"/> <!-- <origin xyz="0 0.0164 -0.00946"/> -->
      <mass value="0.233"/>
      <inertia ixx="3.68e-4" ixy="-7.57e-6" ixz="5.38e-6" iyy="1.16e-4" iyz="-4.8e-5" izz="3.76e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0.04 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Roll_Structure_Left.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0.04 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Roll_Structure_Left.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  
  <joint name="LiCAS_A1_q1_2" type="revolute">
    <origin xyz="0 0.04 0"/>
    <parent link="left_shoulder_roll"/>
    <child link="left_shoulder_yaw"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-20/180*pi}" upper="${90/180*pi}" velocity="6"/>
  </joint>
  
  <link name="left_shoulder_yaw">
    <inertial>
      <origin xyz="-0.015 0 -0.1"/>
      <mass value="0.246"/>
      <inertia ixx="3.49e-4" ixy="0" ixz="-3.79e-5" iyy="4.46e-4" iyz="0" izz="1.49e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Assembly_Shoulder_Yaw_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Assembly_Shoulder_Yaw_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link> 
  
  
  <joint name="LiCAS_A1_q1_3" type="revolute">
    <origin xyz="0 0 -0.143"/>
    <parent link="left_shoulder_yaw"/>
    <child link="left_elbow_pitch"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-90/180*pi}" upper="${90/180*pi}" velocity="6"/>
  </joint>
  
  <link name="left_elbow_pitch">
    <inertial>
      <origin xyz="0 0 -0.093"/>
      <mass value="0.214"/>
      <inertia ixx="4.21e-4" ixy="-7.81e-7" ixz="-4.06e-5" iyy="4.26e-4" iyz="1.8e-5" izz="5.01e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.132"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Elbow_Pitch_Structure_Left_Cut.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.132"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Elbow_Pitch_Structure_Left_Cut.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  
  <joint name="LiCAS_A1_q1_4" type="revolute">
    <origin xyz="0 0 -0.132"/>  
    <parent link="left_elbow_pitch"/>
    <child link="left_forearm_link"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="left_forearm_link">
    <inertial>
      <origin xyz="0 0 -0.092"/>
      <mass value="0.106"/>
      <inertia ixx="3.94e-4" ixy="0" ixz="0" iyy="3.75e-4" iyz="-3.5e-6" izz="3.05e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Forearm_Link_with_Gripper_Servo.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Forearm_Link_with_Gripper_Servo.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link> 
  
  
  <!-- RIGHT ARM-->
  <joint name="LiCAS_A1_q2_1" type="revolute">
    <origin xyz="0 -0.14 0.0"/>
    <parent link="shoulder_link_y"/>
    <child link="right_shoulder_roll"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-90/180*pi}" upper="${90/180*pi}" velocity="6"/>
  </joint>
  
  <link name="right_shoulder_roll">
    <inertial>
      <origin xyz="0 -0.0236 -0.00946"/> <!-- <origin xyz="0 -0.0164 -0.00946"/> -->
      <mass value="0.233"/>
      <inertia ixx="3.68e-4" ixy="7.57e-6" ixz="5.38e-6" iyy="1.16e-4" iyz="4.8e-5" izz="3.76e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 -0.04 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Roll_Structure_Right.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 -0.04 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Shoulder_Roll_Structure_Right.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  
  <joint name="LiCAS_A1_q2_2" type="revolute">
    <origin xyz="0 -0.04 0"/>
    <parent link="right_shoulder_roll"/>
    <child link="right_shoulder_yaw"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-90/180*pi}" upper="${20/180*pi}" velocity="6"/>
  </joint>
  
  <link name="right_shoulder_yaw">
    <inertial>
      <origin xyz="-0.015 0 -0.1"/>
      <mass value="0.246"/>
      <inertia ixx="3.49e-4" ixy="0" ixz="-3.79e-5" iyy="4.46e-4" iyz="0" izz="1.49e-4"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Assembly_Shoulder_Yaw_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Assembly_Shoulder_Yaw_Structure.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link> 
  
  
  <joint name="LiCAS_A1_q2_3" type="revolute">
    <origin xyz="0 0 -0.143"/>  
    <parent link="right_shoulder_yaw"/>
    <child link="right_elbow_pitch"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-90/180*pi}" upper="${90/180*pi}" velocity="6"/>
  </joint> 
  
  <link name="right_elbow_pitch">
    <inertial>
      <origin xyz="0 0 -0.093"/>  
      <mass value="0.214"/>
      <inertia ixx="4.21e-4" ixy="7.81e-7" ixz="-4.06e-5" iyy="4.26e-4" iyz="-1.8e-5" izz="5.01e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.132"/> 
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Elbow_Pitch_Structure_Right_Cut.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.132"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Elbow_Pitch_Structure_Right_Cut.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  
  <joint name="LiCAS_A1_q2_4" type="revolute">
    <origin xyz="0 0 -0.132"/>  
    <parent link="right_elbow_pitch"/>
    <child link="right_forearm_link"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="10.0" lower="${-150/180*pi}" upper="${150/180*pi}" velocity="6"/>
  </joint>
  
  <link name="right_forearm_link">
    <inertial>
      <origin xyz="0 0 -0.092"/>
      <mass value="0.106"/>
      <inertia ixx="3.94e-4" ixy="0" ixz="0" iyy="3.75e-4" iyz="3.5e-6" izz="3.05e-5"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/> 
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Forearm_Link_with_Gripper_Servo.dae" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://uav-cable-suspended-robots-ros-pkg/mesh/licas/Forearm_Link_with_Gripper_Servo.dae" scale=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  
  <!-- END EFFECTORS -->
  
  <joint name="right_eef_joint" type="fixed">
    <origin xyz="0 0 -0.25"/>
    <parent link="right_forearm_link"/>
    <child link="right_eef_link"/>
  </joint>
  
  <link name="right_eef_link">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="1e-3" />
      <inertia ixx="1e-03" ixy="0.0" ixz="0.0" iyy="1e-03" iyz="0.0" izz="1e-03"/>
    </inertial>
  </link>
  
  <joint name="left_eef_joint" type="fixed">
    <origin xyz="0 0 -0.25"/>
    <parent link="left_forearm_link"/>
    <child link="left_eef_link"/>
  </joint>
  
  <link name="left_eef_link">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="1e-3" />
      <inertia ixx="1e-03" ixy="0.0" ixz="0.0" iyy="1e-03" iyz="0.0" izz="1e-03"/>
    </inertial>
  </link> 

  
  <!-- Include MY URDF Files 
  <xacro:include filename="$(find cable-suspended-robots-ros-pkg)/urdf/licasa1.urdf.xacro" /> -->
</robot>
